source 'https://rubygems.org'

gem 'compass', '1.0.0.alpha.19'
gem 'middleman', '3.3.2'
gem 'middleman-livereload', '~> 3.1.0'
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
gem 'compass-placeholders'
gem 'livingstyleguide', path: '..'

platforms :mri_18 do
  gem 'ruby18_source_location'
end

